name: application
description: A project for projects
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  firebase_crashlytics: ^3.3.3
  firebase_messaging: ^14.6.4
  firebase_performance: ^0.9.2+3
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_remote_config: ^4.2.3
  cloud_functions: ^4.3.3
  cloud_firestore: ^4.8.2
  hive: ^2.2.3
  flutter_native_splash: ^2.3.1
  tinycolor2: ^3.0.1
  universal_html: any
  universal_io: any
  uuid: ^3.0.7
  duration: ^3.0.12
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  equatable: ^2.0.5
  http: any
  rxdart: ^0.27.7
  get: ^4.6.5
  flutter_oss_licenses: ^2.0.1
  native_ios_dialog: ^0.2.0
  padded: ^1.0.1
  snackbar: ^1.0.2
  delayed_progress_indicator: ^1.0.1
  memcached: ^1.0.2
  mapped_list: ^1.0.0
  tryhard: ^1.0.1
  flyout: ^1.0.2
  timeago: ^3.4.0
  json_compress: ^1.0.5
  intl: any
  shimmer: ^3.0.0
  collection_walker: ^1.1.0
  precision_stopwatch: ^1.0.2
  threshold: ^1.0.4
  toxic: ^1.0.3
  google_fonts: any
  flutter_animate: ^4.2.0
dev_dependencies:
  icon_font_generator: ^3.2.0
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  dependency_validator: ^3.2.2
flutter_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "../configuration/icon.png"
flutter_gen:
  output: lib/util/generated/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
flutter_native_splash:
  color: "#ffffff"
  image: "../configuration/icon_splash_light.png"
  color_dark: "#000000"
  image_dark: "../configuration/icon_splash_dark.png"
  android: true
  ios: true
  web: true
flutter:
  uses-material-design: true
  fonts:
    - family: IIcons
      fonts:
        - asset: assets/font/iicons.ttf
  assets:
    - assets/icon/icon.svg
    - assets/logo/apple.svg
    - assets/logo/google.svg
