name: application
description: A project for projects
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  firebase_crashlytics: ^3.3.3
  firebase_messaging: ^14.6.4
  firebase_performance: ^0.9.2+3
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_remote_config: ^4.2.3
  cloud_functions: ^4.3.3
  cloud_firestore: ^4.8.2
  hive: ^2.2.3
  flutter_native_splash: ^2.3.1
  tinycolor2: ^3.0.1
  universal_html: any
  universal_io: any
  uuid: ^3.0.7
  duration: ^3.0.12
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  equatable: ^2.0.5
  http: any
  rxdart: ^0.27.7
  get: ^4.6.5
  flutter_oss_licenses: ^2.0.1
  native_ios_dialog: ^0.2.0
  padded: ^1.0.1
  snackbar: ^1.0.2
  delayed_progress_indicator: ^1.0.1
  memcached: ^1.0.2
  mapped_list: ^1.0.0
  serviced: ^1.0.1
  tryhard: ^1.0.1
  flyout: ^1.0.2
  timeago: ^3.4.0
  json_compress: ^1.0.5
  intl: any
  shimmer: ^3.0.0
  collection_walker: ^1.1.0
  precision_stopwatch: ^1.0.2
  threshold: ^1.0.4
  toxic: ^1.0.3
  google_fonts: any
  flutter_animate: ^4.2.0
  fast_log: ^1.0.5
  crypto: ^3.0.3
  flutter_svg: ^2.0.7
  throttled: ^1.0.1
  synchronized: ^3.1.0
  path_provider: ^2.0.15
  quantum: ^1.1.11
dev_dependencies:
  icon_generator: ^4.0.3
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  dependency_validator: ^3.2.2
flutter_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
flutter_gen:
  output: lib/util/generated/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
flutter_native_splash:
  color: "#f3f2ff"
  image: "assets/icon/splash_light.png"
  color_dark: "#151526"
  image_dark: "assets/icon/splash_dark.png"
  android: true
  ios: true
  web: true
flutter:
  uses-material-design: true
  fonts:
    - family: IIcons
      fonts:
        - asset: assets/font/iicons.ttf
  assets:
    - assets/icon/icon.svg
    - assets/icon/apple.svg
    - assets/icon/google.svg
scripts:
  # This script basically does it all. Its slow but it does everything to ensure everything is good.
  update: |
    flutter pub get
    dart pub global activate flutter_gen
    flutter pub run flutter_oss_licenses:generate.dart --output lib/util/generated/oss_licenses.gen.dart
    flutter pub run flutter_launcher_icons:main
    flutter pub global activate icon_generator
    flutter pub run icon_generator --from=assets/icons --out-font=assets/font/iicons.ttf --out-flutter=lib/util/generated/icons.gen.dart --class-name=IIcons --normalize --naming-strategy=snake
    flutter pub run build_runner build --delete-conflicting-outputs
    flutter pub run flutter_native_splash:create
    dart format .
    dart pub global activate auto_const
    dart pub global run auto_const
    flutter pub run dependency_validator

  # Lists dependencies you (probably) arent using for reducing app size
  validate_dependencies: |
    flutter pub get
    flutter pub run dependency_validator

  # Formats all dart sources and auto applies const everywhere it should be
  format_sources: |
    dart format .
    dart pub global activate auto_const
    dart pub global run auto_const

  # Generates a native splash screen based on the flutter_native_splash configuration above
  update_app_splash: |
    flutter pub run flutter_native_splash:create

  # Generates all the icons for the app based on the flutter_icons configuration above
  update_app_icon: |
    flutter pub run flutter_launcher_icons:main

  # Generates a custom font ttf and class to access icons. Generates them from svgs in the icons folder.
  update_icon_font: |
    flutter pub global activate icon_generator
    flutter pub run icon_generator --from=assets/icons --out-font=assets/font/iicons.ttf --out-flutter=lib/util/generated/icons.gen.dart --class-name=IIcons --normalize --naming-strategy=snake

  # Generates all json models using json_serializable
  update_json_models: |
    flutter pub run build_runner build

  # If your changes are too significant or it fails for some reason use the force script. Slow but works
  update_json_models_force: |
    flutter pub run build_runner build --delete-conflicting-outputs

  # Gathers all the packages you use directly and indirectly and creates a class with all the data in it.
  update_oss_licenses: |
    flutter pub run flutter_oss_licenses:generate.dart --output lib/util/generated/oss_licenses.gen.dart

  firebase_init: |
    firebase login
    flutter pub global activate flutterfire_cli
    dart pub global run flutterfire_cli:flutterfire configure

  # If pod install isnt working and repo update isnt either, this deletes the podfile lock
  fucking_pods:
    script: |
      rm Podfile.lock
      pod install --repo-update
